### ISSUE TITLE
advancePosition should skip comments

### ISSUE THREAD

**Issue by pimentel** [pimentel/atom-r-exec#22]
`advancePosition` should skip comments when advancing.

**Comment by dtenenba** [comment]
It looks like this has been implemented? At least it's the behavior for me. I wonder if it can be an option? There are times when I want to send comments to the terminal...

**Comment by pimentel** [comment]
@dtenenba indeed. I will definitely make it an option in the next version. Anyway, you can send comments using the selection.

I will leave this issue open until I make it an option

**Comment by pimentel** [comment]
now an option in the master branch https://github.com/pimentel/atom-r-exec/commit/6e5f69bca3d764bbacc714e94830eec008844b11
