### ISSUE TITLE
general support for any language/text?

### ISSUE THREAD

**Issue by dtenenba** [pimentel/atom-r-exec#26]
While I do develop in R, I also develop in other languages. 
Sending text from atom to the terminal (or other user-designated app) is very useful in general, not only with R. Sublime Text has [SendText](https://github.com/wch/SendText) a general-purpose plugin for sending any kind of text to the terminal.

Is there any reason why atom-r-exec could not be used with any language (or even plain text)? If so I would suggest the name and documentation change to reflect its general purpose nature.

Also perhaps some features could be generalized, for example the  "advancing past comments" could take into account the different comment symbols in different languages.

**Comment by pimentel** [comment]
thanks for the suggestion, @dtenenba 

I have definitely considered it. one thing that has kept me from doing this is that I particularly like having the language specific niceties such as  sending functions and knitr blocks.

It is certainly possible to generalize some of those things, but it starts getting complicated if you want to support many different languages. We could certainly factor out just the simple `cmd-return` stuff, but it would take considerable effort to factor out and generalize the other stuff.

one possibility is to factor out the simple stuff like `cmd-return` to a basic package that has simple functionality and then make language specific plug-ins. ideally, I would like to do that in the future. realistically though, I don't really have the time right now. I would be willing to help someone if they are interested in doing the heavy lifting though.

**Comment by pimentel** [comment]
moving conversation to #33 and closing this one.
