### ISSUE TITLE
sends text to the "wrong" tab in a group of iTerm tabs

### ISSUE THREAD

**Issue by dtenenba** [pimentel/atom-r-exec#29]
I select some text and press command-enter. I have a group of iTerm tabs but the text is sent to one of the non-selected (non-foreground, non-focused tabs).

**Comment by pimentel** [comment]
Can you give me the following:

- Version of iTerm
- Version of Atom
- Version of r-exec

?

**Comment by dtenenba** [comment]
@pimentel 
Atom 1.5.4
iTerm 2.1.4
r-exec 0.3.4
Thanks.

**Comment by dtenenba** [comment]
Any news on this?
Thanks.

**Comment by pimentel** [comment]
Hi @dtenenba,

Sorry, I've been quite busy and this is a fun side project for me.

Have you upgraded to iTerm 2 build 3? If so, try out the new `iTerm2` mode in `atom-r-exec` and let me know if you are still having problems.

Thanks,

Harold
