### ISSUE TITLE
resend same command

### ISSUE THREAD

**Issue by dschneiderch** [pimentel/atom-r-exec#35]
Nice work on this. reminds me of r-box from Sublime.  it's super useful in my case because I have to run a lot of things on a cluster and can't stand being handcuffed by emacs/vim etc.

i've slowly added some keymappings to resemble rstudio but one feature I'd love to see is "resend last command", e.g. when you're working on a block of code and need to constantly rerun something. Thanks!

**Comment by pimentel** [comment]
Thanks for the kind words, @dschneiderch !

Are you talking about the behavior in RStudio when you type ` cmd-shift-P`? That should be pretty easy.

Any ideas on what we should bind it to? Unfortunately, `cmd-shift-P` is already bound to something in Atom.

**Comment by pimentel** [comment]
and just to be clear, I imagine you are using `advancePosition`? because otherwise the highlighted block will remain highlighted. (or at least it should -- if it is not, please file a bug report)

**Comment by dschneiderch** [comment]
Yes,  cmd+shift+p. I'm using advancePosition=TRUE (this is a major benefit
over rstudio IMO)
how about alt-shift-p ?
alt-shift-? seem to be good candidates for r things.

I'm also using:
'atom-text-editor':
  'shift-alt-m': 'rstudio:insert-pipe'
  'alt--': 'rstudio:insert-assign'

with init.coffee:
atom.commands.add 'atom-text-editor',
  'rstudio:insert-pipe': ->
    atom.workspace.getActiveTextEditor()?.insertText(' %>% ')
  'rstudio:insert-assign': ->
    atom.workspace.getActiveTextEditor()?.insertText(' <- ')


Thanks!

**Comment by pimentel** [comment]
Cool, thanks for the response. I will probably implement run previous command at the end of this week and make a new release with a few bug fixes early next week.

I've been meaning to add those key bindings as well (for assign and pipe).

Thanks,

Harold

**Comment by pimentel** [comment]
Hey there @dschneiderch. Sorry this took so long...

Anyway, it is now in the latest version (I just pushed so please update your package). It currently has a 'smart' insert mode which detects if there is whitespace to the left or right of the cursor and inserts whitespace accordingly. This behave strangely when there is a selection (I can't tell if there is a way to check if there is a current selection in Atom) I suppose the easiest workflow is simply to delete what is under the cursor then use the insert operator.

I used your suggested mappings as well.

Thanks for the suggestions and let me know if you like/dislike any of the new features/behavior.
