### ISSUE TITLE
How to insert the pipe operator?

### ISSUE THREAD

**Issue by hugeme** [pimentel/atom-r-exec#37]
Hi, I just cant figure out how to insert the pipe %>% via some key binding. I have tried the usual suspect shift+command+M. But that is already taken. After disabling the default key bindings of the r-exec I still could not use that binding (I suppose I have to define it explicitly somehow.) Nevertheless, I have loaded dplyr and pasted %>% which however returned "unknown function". DO I miss something here?
Appreciate your help!

**Comment by pimentel** [comment]
Hey there @hugeme !

Totally my fault... I forgot to document it in the README.md

Anyway, you can find all of the default mappings here: https://github.com/pimentel/atom-r-exec/blob/master/keymaps/r-exec.cson

You should be able to simply type `shift-alt-m` and it should work.

Please let me know how it goes.


Thanks

**Comment by pimentel** [comment]
documentation has been improved in `master`. will update the package by the end of the week.
