### ISSUE TITLE
Advance position skips lines that end with # comments

### ISSUE THREAD

**Issue by ekhco** [pimentel/atom-r-exec#38]
```
head(inertial_signals_test[[1]])
nrow(inertial_signals_test[[1]])   # 2947 samples
ncol(inertial_signals_test[[1]])   # 128 cols

table(y_test)
```
In the above code, if the Cursor is on the first line, and Advance Position == TRUE, then it skips over line 2,3 to line 5.

**Comment by pimentel** [comment]
Gah. Good find. This seems like an easy fix -- I will update this weekend.

Thanks.

**Comment by pimentel** [comment]
Fixed in the master branch (you can install this if you would like).

I will push a patch in the coming days after fixing a few other minor bugs.


Thanks again,

Harold

**Comment by ekhco** [comment]
nice! thanks - awesome package btw.

a suggested feature: perhaps you could allow the user to set different
keystrokes to send to different Apps. ie: cmd+enter: R.app,
shift+cmd+enter: Terminal

- Eric

**Comment by pimentel** [comment]
Great idea. The initial version of this project had different keys bound to different destinations which made it a bit confusing. I think I will basically support commands and allow the user to bind those themselves.

Opened issue #40
