### ISSUE TITLE
send to Rstudio?

### ISSUE THREAD

**Issue by sdaza** [pimentel/atom-r-exec#42]
It would be nice if the code can be sent to RStudio like the R-Box package in Sublime Text.

https://github.com/randy3k/R-Box

Thanks!

**Comment by pimentel** [comment]
Looks easy -- sure

**Comment by pimentel** [comment]
Currently implemented in the master branch. Implementing a few more bug fixes and features. Will update and push the package sometime next week.

**Comment by sdaza** [comment]
Great, thanks!
