### ISSUE TITLE
Q/FIX: very silly issue: none of the commands / short cuts seem to work on my setup.

### ISSUE THREAD

**Issue by dengemann** [pimentel/atom-r-exec#9]
Mac OS X 10.10, most recent R binaries. Most recent Atom versions.
I don't know where to start debugging.
Any hints would be welcomed.

**Comment by hafen** [comment]
I just made some updates to be current with the API.  See if it works now.  The package is quite minimal right now, but hope to see more functionality in the future.

**Comment by pimentel** [comment]
@dengemann is this still an issue? the package has changed a fair bit since May. Please let me know if it is.

**Comment by pschloss** [comment]
I'm unable to get cmd-enter to work with a fresh install of r-exec trying to get it to go to Terminal in Mac 10.11. Suggestions on what to try?

**Comment by pimentel** [comment]
@pschloss did you add the following to your `~/.atom/keymap.cson`

```js
'atom-workspace atom-text-editor:not([mini])':
  'cmd-enter': 'r-exec:send-command'
```

? If that doesn't work, try replacing it with the following:

```js
'atom-workspace atom-text-editor':
  'cmd-enter': 'r-exec:send-command'
```

Keep me posted. Do the other key bindings work?

**Comment by pschloss** [comment]
Sorry, my bad, I clearly didn't read far enough in the instructions. The first one worked. Thanks for this great package!
